#################
# Docker file to run the rest tests for the packages
################
#
# Run with volumes configured appropriately, like this
#
# 1. Build the container
#    docker build -f src/test/docker/Dockerfile-fedora -t elasticsearch-rest-tests-fedora src/test/docker
# 2. Run the tests
#    docker run -v $PWD:/elasticsearch -v $HOME/.m2:/root/.m2 elasticsearch-rest-tests-fedora /run-tests-rpm.sh
#
FROM fedora:latest
MAINTAINER Elasticsearch <info@elasticsearch.com>

RUN yum -y update
RUN yum -y install java-1.8.0-openjdk-devel.x86_64 curl rpm-devel rpm-build maven

ADD run-tests-rpm.sh /run-tests-rpm.sh
VOLUME /elasticsearch
VOLUME /root/.m2


